**Exercício 01:** Uma matriz xadrez segue o seguinte padrão:

```
[[0,1]
[1,0]]
```

Construa uma matriz 8x8 na variável `matriz` com esse padrão.

Faça uma variável `matriz2`, também 8x8, sem utilizar o comando `for`.

In [29]:
# crie uma matriz 8 x 8 com valores em forma de xadrez 0,1
import numpy as np

p1=np.array([0.,1]) 
p2=np.array([1,0])
y1=np.resize(p1, (1, 8))
y2=np.resize(p2, (1, 8))
a=np.concatenate((y1, y2))
matriz=np.resize(a, (8, 8))
matriz2=np.concatenate((y2, y1))
b=np.concatenate((y2,y1))
matriz2=np.resize(b, (8, 8))

print matriz, '\n'  
print matriz2, '\n'

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]] 

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]] 



Opção 2:

import numpy as np 

matriz = np.zeros([8,8])
for i in range(0,8):
    #for j in range (0,8):
        #if (i+j)%2:
            #matriz[i,j]=1

**Exercício 02:** Uma matriz normalizada é definda por:

$$
n_{ij} = \frac{a_{ij} - min(A)}{max(A)-min(A)}
$$

Normalize a matriz abaixo.

In [50]:
# normalize uma matriz
matriz = np.array( [[3.,2.,1.,5.,1.],[2.,1.,4.,5.,1.],[5.,2.,1.,5.,3.] ] )
matriz2 = np.zeros_like(matriz)
a=matriz.max()
b=matriz.min()
for i in range (3):
    for j in range (5):
        matriz2[i,j]= ((matriz[i,j] - b)/(a-b))

        
print matriz2


[[ 0.5   0.25  0.    1.    0.  ]
 [ 0.25  0.    0.75  1.    0.  ]
 [ 1.    0.25  0.    1.    0.5 ]]


**Exercício 03:** A matriz Z representa uma matriz com coordenadas cartesianas, converta cada linha para coordenada polar, dado que:

$$
X, Y -> \rho, \theta \\
\rho = \sqrt(X^2 + Y^2) \\
\theta = arctan2(Y,X)
$$

Faça utilizando laço `for` (em Z2) e sem usar laços (Z3).

In [3]:
import numpy as np
# converter matriz N x 2 representando coordenadas cartesianas em polares
Z = np.array([[10.,2.],[5.,3.5],[1.2,4.1],[3.2,3.14]])
Z2 = np.zeros_like(Z)
Z3 = np.zeros_like(Z)

for i in range (4):
    Z2[i,0] = np.sqrt(Z[i][0]**2+Z[i][1]**2)
    Z2[i,1] = np.arctan2(Z[i][1], Z[i][0])
        



print Z2
print
print Z3

[[ 10.19803903   0.19739556]
 [  6.10327781   0.61072596]
 [  4.27200187   1.28606589]
 [  4.48325774   0.77593472]]

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


**Exercício 04:** Substitua o maior valor da matriz Z por 0 e mostre o novo maior valor

In [32]:
# função que substitui o maior valor por 0 e retorna o maior valor
Z = np.array([[10.,2.],[5.,3.5],[1.2,4.1],[3.2,3.14]])
def subs(Z):
    pos_i=0
    pos_j=0
    maior = Z[0][0]
    for i in range(0,len(Z)):
        for j in range(0,len(Z[0])):
            if Z[i][j]>maior:
                maior = Z[i][j]
                pos_i=i
                pos_j=j
            
    Z[pos_i][pos_j] = 0
    return Z.max()

print subs(Z)


5.0


**Exercício 05:** Dado um vetor X e uma matriz Y, construa um vetor D em que cada elemento i é a distância Euclidiana entre X e o i-ésimo elemento de Y.

In [50]:
# calcule a distância euclidiana entre x e uma matriz de pontos Y
import math
X = np.array([ 0.17, 0.59, 0.75, 0.78,0.47, 0.10, 0.06,0.37,0.66,0.10])
Y = np.array( [[ 0.82,  0.96,  0.53,  0.61,  0.76,  0.3,   0.95,  0.81,  0.53,  0.84],
 [ 0.7,   0.49,  0.07,  0.12,  0.87,  0.73,  0.73,  0.39,  0.46,  0.37],
 [ 0.54,  0.79,  0.66,  0.27,  0.79,  0.33,  0.36,  0.83,  0.22,  0.17],
 [ 0.96,  0.63,  0.5 ,  0.88,  0.45,  0.9,   0.12,  0.92,  0.7 ,  0.79],
 [ 0.6 ,  0.02,  0.39,  0.29,  0.33,  0.07,  0.35,  0.31,  0.38,  0.84]])
D = np.zeros_like(X)

for i in range(0,len(X)):
    for j in range(0, len(Y[0])):
        D[i,j] = math.sqrt((X[i,j]**2)+(Y[i,j]**2))

print D


IndexError: too many indices for array

**Exercício 06:** Mostre o elemento com a menor distância de X e qual é essa distância.

In [28]:
# encontre o ponto mais próximo do exercicio anterior


1.04904718674 2
