**Exercícios de Revisão: Vetor**

**1.**	Faça um programa que receba um vetor V de N inteiros e imprima os elementos pares do vetor V.

**2.**	Faça um programa que receba um vetor V de N inteiros e imprima os elementos que estão nos índices pares do vetor V.

**3.**	Faça um programa para imprimir uma lista de nomes de alunos com nota superior a média da turma.

**4.**	Faça um programa para imprimir uma lista de nomes invertendo duas posições quaisquer desta lista.

**5.**	Faça um programa que receba uma quantidade indefinida de números inteiros e ao final mostre qual o maior deles e a quantidade de vezes que ele foi informado.

**6.**	Faça um programa que ordene uma vetor de N inteiros.

In [1]:
import numpy as np

V=np.array([[1,3,4,5],[3,6,8,6],[3,6,4,3]])
def Pares(V):
    m,n=V.shape
    for i in range(m):
        for j in range(n):
            if V[i,j]%2==0:
                print V[i,j]

print Pares (V)

4
6
8
6
6
4
None


In [10]:
import numpy as np

V=np.array([[1,3,4,5],[3,6,8,6],[3,6,4,3]])
M = np.zeros_like(V)
def Pares(V):
    m,n=V.shape
    for i in range(m):
        for j in range(n):
            if j%2==0 or i%2==0:
                print V[i,j]

print Pares (V)

1
3
4
5
3
8
3
6
4
3
None


In [9]:
import numpy as np
a=np.array([2,5,6,9,8,5,6])
b=np.array(["A","B","C","D","E","F","G"])
x=0
lista=[]

for i in range(len(a)):
    x=x+a[i]

y=x/len(a)
print y

for i in range(len(a)):
    if a[i]>y:
        lista.append(b[i])

print lista
    


5
['C', 'D', 'E', 'G']


In [ ]:
b=np.array(["A","B","C","D","E","F","G"])
lista=[]

for i in range (len(w)):
    a[i]=
    


In [11]:
a=np.random.random([1,5,6,9,8,5,1,2,5,8,4,6,10]) 

for i in range(len(a))


[[ 0.24354896  0.28728696  0.86660297  0.2379967   0.20669753  0.393879
   0.37844875  0.86247994  0.24852063]]


**Exercícios de Revisão: Matriz**

**1.**	Faça um programa que recebe duas matrizes A e B, ambas de tamanho N por N. Este programa deve mostrar a matriz A+B ou seja a matriz resultante da soma termo a termo da matriz A com a matriz B. Para esta questão fazer três funções: lerMatriz() para retornar uma matriz lida do teclado; somaMatriz(A,B) que recebe duas matrizes de mesmo tamanho e retorna uma outra matriz com a somo; imprimeMatriz(A) para imprimir uma matriz A. Estas funções deverão ser chamadas do programa principal.


**2.** Faça um programa que receba uma matriz NxN e apresente o valor da soma dos componentes de cada linha da matriz.

**3.** Faça um programa que receba uma matriz NxN, calcule a transposta com a função transpostaMatriz(A), e imprima a matriz transposta.

**4.** Faça um programa que recebe duas matrizes A e B, ambas de tamanho N por Q e Q por M, respectivamente. Este programa deve mostrar a matriz A*B ou seja a matriz resultante da multiplicação da matriz A com a matriz B. Use as funções de ler e imprimir matriz da primeira questão.

In [ ]:
def Matriz():
    def lerMatriz():
        m,n=A.shape
        m,n=B.shape
        for i in range(n):
            for j in range(m):
                
    def somaMatriz(A,B):
        print A+B
    def imprimeMatriz(A):
        print A
                

In [3]:
import numpy as np

A=np.array([[1,3,4,1],[3,6,8,1],[3,6,4,1],[1,3,4,1]])
def Matriz(A):
    a=0
    m,n=A.shape
    for i in range (m):
        for j in range (n):
            a=a+A[j]
        return a
    
print Matriz(A)

[ 8 18 20  4]


In [11]:
def TranspostaMatriz(A):
    m,n = A.shape
    transposta = []
    for i in range (m):
        linha_transposta = []
        for linha in A:
            linha_transposta.append(linha[i])
        transposta.append(linha_transposta)
    return transposta    

print TranspostaMatriz(A)

[[1, 3, 3, 1], [3, 6, 6, 3], [4, 8, 4, 4], [1, 1, 1, 1]]


In [7]:
import numpy as np

A=np.array([[1,3,4,1],[3,6,8,1],[3,6,4,1]])
B=np.array([[1,3,4],[3,6,8],[3,6,4],[1,3,4]])

def Multipl(A,B):
    m,n=A.shape
    r,s=B.shape
    C=np.zeros((m,s))
    for i in range(m):
        for j in range(n):


    
print Multipl(A,B)

IndexError: index 3 is out of bounds for axis 0 with size 3



**Exercícios de Revisão: outros **

**1.**	Escreva um programa ler dois vetores (A e B) de 10 elementos cada, usando módulo int [] lerVetor(). Após a entrada de dados, o programa deve: Obter e exibir a soma dos elementos do vetor A; Obter e exibir a soma dos elementos do vetor B; Calcular e exibir a média dos elementos dos dois vetores (uma única média); Imprimir o vetor A e depois o vetor B; Mostrar os elementos de A e B que são acima da média de ambos. Fazer módulos para todos estes itens, que deverão ser chamados no módulo principal main.

**2.** Escreva a função ValidaInteiro para solicitar um número inteiro e validá-lo de forma que o mesmo  esteja dentro de um intervalo. Os limites do intervalo serão passados por parâmetro. Escreva também a função principal (início) para fazer a chamada da função com os seguintes valores:
ValidaInteiro (0, 100)    // aceitar valores entre 0 e 100
ValidaInteiro (-50, 50)  // aceitar valores entre -50 e 50
Atenção:  O número deve ser lido dentro da função e o valor (válido) deve ser retornado pela função.

**3.** Construa uma função que receba, por parâmetro, uma matriz (preenchida) e suas respectivas dimensões e retorne V (verdadeiro) se existir alguma linha com todos os elementos zerados e F (falso) caso contrário. 

**4.** Faça um programa para ler dois números inteiros positivos X e Y (1 ≤ X < Y ≤ 10000), os tempos, em segundos, que um piloto mais rápido e o piloto mais lento levam para completar uma volta em uma pista de corrida, respectivamente. Seu programa deve produzir uma única linha de saída, contendo um único inteiro: a volta em que o piloto mais lento se tornará um retardatário. Ex. In 1 10, Out 2;  In 5 7, Out 4; In 6875 7109, Out 31.

**5.** Faça um programa em que receba uma sequencia de palavras e indique se ela é ou não um palíndromo (igual se lida tanto da direita para a esquerda). Ex. salas e osso são palíndromos. A entrada do programa consiste de várias palavras, uma por linha com comprimento máximo de 200 caracteres por palavra. A entrada termina com EOF. A saída consiste de várias linhas, uma para cada palavra. Você deve imprimir a palavra “sim”, caso a palavra seja palíndromo; ou “nao”, caso contrário. 

In [25]:
def SomaElem(X):
    m,n=X.shape
    a=0
    for i in range (m):
        for j in range (n):
            a=a+X[i,j]
        return a

print SomaElem(A)

9


In [3]:
# crie uma matriz 8 x 8 com valores em forma de xadrez 0,1
import numpy as np
matriz=np.zeros([8,8])
for i in range(0,8):
    for j in range (0,8):
        if (i+j)%2:
            matriz[i,j]=1

print matriz
print
matriz2 = np.array([[0.,1.]*4,[1.,0.]*4]*4)
print matriz2


[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


**Exercício 02:** Uma matriz normalizada é definda por:

$$
n_{ij} = \frac{a_{ij} - min(A)}{max(A)-min(A)}
$$

Normalize a matriz abaixo.

In [4]:
# normalize uma matriz
matriz = np.array( [[3.,2.,1.,5.,1.],[2.,1.,4.,5.,1.],[5.,2.,1.,5.,3.] ] )
matriz2 = matriz

min = matriz.min()
denom = matriz.max()-min

for i in range(0,matriz.shape[0]): #linhas i
    for j in range(0,matriz.shape[1]): #coluna j
        matriz2[i,j] = (matriz[i,j]-min)/denom

print matriz

[[ 0.5   0.25  0.    1.    0.  ]
 [ 0.25  0.    0.75  1.    0.  ]
 [ 1.    0.25  0.    1.    0.5 ]]
